services:
  mysql:
    image: mysql:8.4.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

#  spring-ai-app:
#    image:
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/chatdb
#      SPRING_DATASOURCE_USERNAME: chatuser
#      SPRING_DATASOURCE_PASSWORD: chatpass
#    ports:
#      - "8080:8080"

volumes:
  mysql_volume: