spring:
  application:
    name: spring-ai-intro
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
#          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4.1-2025-04-14
          temperature: 0.3
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:/mcp-servers-config.json
    mcp:
      server:
        enabled: true
        name:  customer-score-server
        sse-message-endpoint: /mcp/message
        sse-endpoint: sse
        version: 1.0.0
#        type: SYNC
        instructions: "This server provides customer score information tools and resources"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
      client:
#        type: ASYNC
        request-timeout: 60s
        stdio:
          connections:
            brave-search:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}
              filesystem:
                command: npx
                args:
                  - "-y"
                  - "@modelcontextprotocol/server-filesystem"
                  - "./"
#        sse:
#          connections:
#            customer-score-server:
#              url: "http://localhost:8080"

  output:
    ansi:
      enabled: ALWAYS

sfg:
  aiapp:
    vector-store-enabled: true
    # vectorStorePath: /tmp/vectorstore.json
    vectorStorePath: vector-store/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai.mcp.client.transport.StdioClientTransport: DEBUG
    org.springframework.ai.mcp.samples.brave: DEBUG
    io.modelcontextprotocol.client: DEBUG
    io.modelcontextprotocol.spec: DEBUG