spring:
  application:
    name: spring-ai-intro
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
#          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4.1-2025-04-14
          temperature: 0.3
      image:
        options:
          model: dall-e-2
          temperature: 0.3
    vectorstore:
      type: none # comment this line to enable Milvus
      milvus:
        initialize-schema: true
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        # indexType: IVF_FLAT
        metricType: COSINE
        indexType: HNSW
        indexParameters:
          M: 48  # Increased from 16 → better connectivity
          efConstruction: 100  # Reduced from 200 → faster builds
        searchParameters:
          ef: 32  # Reduced from 100 → faster searches
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:/mcp-servers-config.json
    mcp:
      server:
        enabled: true
        name:  customer-score-server
        sse-message-endpoint: /mcp/message
        sse-endpoint: sse
        version: 1.0.0
#        type: SYNC
        instructions: "This server provides customer score information tools and resources"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
      client:
#        type: ASYNC
        request-timeout: 60s
        stdio:
          connections:
            brave-search:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}
              filesystem:
                command: npx
                args:
                  - "-y"
                  - "@modelcontextprotocol/server-filesystem"
                  - "./"
#        sse:
#          connections:
#            customer-score-server:
#              url: "http://localhost:8080"

  output:
    ansi:
      enabled: ALWAYS

sfg:
  aiapp:
    ninjas-api-key: ${NINJAS_API_KEY}
    vector-store-local: true # change to false to enable Milvus
    vector-store-enabled: true
    # vectorStorePath: /tmp/vectorstore.json
    vectorStorePath: vector-store/vectorstore.json
    documentsToLoad:
#      - classpath:/movies500Trimmed.csv
      - classpath:/towvehicles.txt
      # Sportsman 212 - Weight 3,458 lbs
      - https://yamahaoutboards.com/outboards/350-150-hp/in-line-4/f150-(i4)/pb_spt_open_212_f150xb_9-10-2020-occ
      # Sportsman 232 - Weight 5,001 lbs
      - https://yamahaoutboards.com/outboards/350-150-hp/v6-4-2l/f300-(4-2l)/pb_spt_open-232_f300xsb2_6-29-2023_occ
      # Sportsman 322 - Weight 12,469 lbs
      - https://yamahaoutboards.com/outboards/xto-offshore/v8-5-6l/xf425/pb_spt_open-322_tw_lxf425usb2_8-26-2021_occ
      # Scout 380 LXF - Weight 19,443 lbs
      - https://yamahaoutboards.com/outboards/xto-offshore/v8-5-6l/xf425/pb_sct_380lxf_tr_xf425_8-30-2018_occ

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai.mcp.client.transport.StdioClientTransport: DEBUG
    org.springframework.ai.mcp.samples.brave: DEBUG
    io.modelcontextprotocol.client: DEBUG
    io.modelcontextprotocol.spec: DEBUG