spring:
  application:
    name: spring-ai-intro
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
#          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4.1-2025-04-14
          temperature: 0.3
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json
  output:
    ansi:
      enabled: ALWAYS

sfg:
  aiapp:
    vector-store-enabled: true
    # vectorStorePath: /tmp/vectorstore.json
    vectorStorePath: vector-store/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv

logging:
  level:
    root: INFO
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai.mcp.client.transport.StdioClientTransport: DEBUG
    org.springframework.ai.mcp.samples.brave: DEBUG
    io.modelcontextprotocol.client: DEBUG
    io.modelcontextprotocol.spec: DEBUG